### ISSUE TITLE
Globalization

### ISSUE THREAD

**Issue by LuisFX** [Dzoukr/Yobo#17]
Hi, I am currently adding selectable english and spanish translations to this project. If interested, I'll do a pr and commit back to this repo.

**Comment by Dzoukr** [comment]
Hi @LuisFX, thanks for an offer, but I don't plan to run it anywhere else than in my wife's yoga class in Czech Republic. To fully understand, it's not meant to be OSS project - I just wanted to share ("have a look" way) how I figured out some problems with F# and Fable. You can still use it, but please be aware that all the graphical content (logo) and texts are part of my wife's copyright, so if you want to run it somewhere else with different language, you'll need to change logo and brands.

I'll make some statement on README.md to make it clear.

Anyway, I appreciate your offer!

**Comment by LuisFX** [comment]
Got it. Thank you for the clarification. I do not intend to use the application as it. I just needed to understand what all was happening, and so I decided to globalize it for my own understanding!

Thank you anyway for a great contribution.

L
